name: EXT4 Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build kernel docker image
      run: docker build . --file Dockerfile --tag kernel:$(date +%s)
